#!/usr/bin/php
<?php
if($argc < 2)
	die("Format: checkSpelling {word}");
$pspell = pspell_new("en");
if(!pspell_check($pspell, $argv[1])) {
	echo "Invalid word: ".$argv[1]."\n";
	$suggestions = pspell_suggest($pspell, $argv[1]);
	foreach ($suggestions as $i => $suggestion) {
		if($i >= 10)
			break;
		echo "Possible spelling: $suggestion\n";
	}
}else
	echo "No spelling error";
