#!/bin/php
<?php
$currentWindowId = trim(`xdotool getwindowfocus`);
$accounts = explode("\n", `lpass ls -l --sync=no | regexify -g "#[0-9]{4}\-[0-9]{2}\-[0-9]{2} [0-9]{2}\:[0-9]{2} .*/(.*) \[id: (.*)\] \[username: (.*)\]#"`);
$accountToId = [];
$searchableAccounts = "";
foreach($accounts as $account) {
	if(trim($account) == "") // ignore empty lines
		continue;
	$parts = explode("\t", $account);
	$search = $parts[0]." (".$parts[2].")";
	$id = $parts[1];
	$accountToId[$search] = $id;
	$searchableAccounts .= $search."\n";
}
$searchableAccounts = escapeshellarg($searchableAccounts);
$selection = trim(`echo $searchableAccounts | dmenu -w $currentWindowId -l 10 -i -p "Website?"`);
if($selection == "") {
	echo "Nothing selected.";
	exit(1);
}

if(!isset($accountToId[$selection])) {
	echo "Invalid selection.";
	exit(1);
}

$account = $accountToId[$selection];
$tty = `tty`;

switch($argv[1]) {
	case "username":
		`lpass show $account --username -c > $tty`;
		`notify-send "rofiLastpass" "Username for $selection copied to clipboard"`;
		break;
	case "password":
		`lpass show $account --password -c > $tty`;
		`notify-send "rofiLastpass" "Password for $selection copied to clipboard"`;
	break;
}
