#!/bin/zsh
currentWindowId=$(xdotool getwindowfocus);
accounts=$(lpass ls -l --sync=no)
accounts=$(echo $accounts | regexify -g "#[0-9]{4}\-[0-9]{2}\-[0-9]{2} [0-9]{2}\:[0-9]{2} .*/(.*) \[id: (.*)\] \[username: (.*)\]#")
declare -A accountToId
searchableAccounts=""
while IFS= read -r account; do # this part is so freaking slow I should probably do this in something faster than shell script...
	search=$(echo $account | awk -F"\t" '{ print $1" ("$3") " }')
	id=$(echo $account | awk -F"\t" '{ print $2 }')
	accountToId[$search]="$id"
	searchableAccounts="$searchableAccounts$search\n"
done <<< "$accounts"
selection=$(echo $searchableAccounts | dmenu -w $currentWindowId -l 10 -i -p "Website?")
if [[ "$selection" == "" ]]; then
	echo "Nothing selected."
	exit 1
fi
if [[ "${accountToId[$selection]}" == "" ]]; then
	echo "Invalid selection."
	exit 1
fi
if [[ "$1" == "username" ]]; then
	lpass show ${accountToId[$selection]} --username -c
	notify-send "rofiLastpass" "Username for $selection copied to clipboard"
fi
if [[ "$1" == "password" ]]; then
	lpass show ${accountToId[$selection]} --password -c
	notify-send "rofiLastpass" "Password for $selection copied to clipboard"
fi
# 2019-09-13 17:55 wolframalpha.com [id: 636060507226998819] [username: danny.morabito@icloud.com]
