#!/usr/bin/env bash

shopt -s nullglob globstar

if [[ $1 == "add" ]]; then
	notify-send "Creating new password"
	website=$(echo "" | dmenu -l 1 -i -p "Website?")
	[[ -n $website ]] && exit 1;
	account=$(echo "" | dmenu -l 1 -i -p "Username?")
	[[ -n $account ]] && account="thelmuxkriovar@pm.me"
	pass generate "${website}[${account}] 16"
	notify-send "Password for $website created" "Username: $account\nPassword: <i>Copied to clipboard</i>"
	exit 0
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

account=$(printf '%s\n' "${password_files[@]}" | dmenu -l 10 -i -p "Website?")
[[ -n $account ]] || exit
website=( "${account%[*}" )

if [[ "$1" == "username" ]]; then
	account=( "${account#*[}" )
	account=( "${account%]}" )
	echo $account | xclip -i -selection clipboard
	notify-send "dmenuPass" "Username for $website copied to clipboard"
	exit 0
fi

if [[ "$1" == "password" ]]; then
	pass show -c "$account" 2>/dev/null
	notify-send "dmenuPass" "Password for $website copied to clipboard"
	exit 0
fi

exit 1
