#!/bin/sh

selectedPage=$(find /usr/share/man/man*/ | grep .gz | sed 's#/usr/share/man/man./##' | sed 's#...gz##' | sed 's#\.$##' | sort | uniq | rofi -dmenu -i -p "Page Name")
tmpFile=$(mktemp --suffix ".pdf")
[[ $selectedPage == "" ]] && exit 1
man -Tpdf $selectedPage >> $tmpFile
zathura $tmpFile --fork