#!/bin/sh
selectedPage=$(apropos . | dmenu -l 30 -i -p "Page Name" | awk '{ print $1 }')
tmpFile=$(mktemp --suffix ".pdf")
[[ $selectedPage == "" ]] && exit 1
man -t $selectedPage | ps2pdf - $tmpFile
zathura $tmpFile --fork
