#!/usr/bin/php
<?php
$oldWidth = 0;
$oldHeight = 0;
function progressBarStr(float $progress = 0, int $width = 0) {
	$progress = min(1, max(0, $progress));
	$wholeWidth = floor($progress * $width);
	$remainderWidth = ($progress * $width) % 1;
	$partialWidth = floor($remainderWidth * 8);
	$remaining = $width - $wholeWidth - 1;
	if($remaining < 0)
		$partialChar = "";
	else
		$partialChar = ["░", "▏", "▎", "▍", "▌", "▋", "▊", "▉"][$partialWidth];
	$line = "";
	if($wholeWidth > 0)
		$line = str_repeat("█", $wholeWidth);
	$line .= $partialChar;
	if($remaining > 0)
	   $line .= str_repeat("░", $remaining);
	return $line;
}
// original code from https://stackoverflow.com/a/2510540
function toBytes($number, $startingUnit = 1) {
	$base = log($number, 1024);
	$bases = ["", "k", "M", "G", "T", "P"];
	return number_format(pow(1024, $base - floor($base)), 2).$bases[floor($base) + $startingUnit];
}
while(true) {
	$disks = explode("\n", `df -x tmpfs -x devtmpfs | grep -v /boot | sed -n '1!p' | awk '{ print $1"\t"$3"\t"$4"\t"$6}'`);
	array_pop($disks); // remove the last line (empty blank line)
	$longestMountPoint = 0;
	$disks = array_map(function($disk) use(&$longestMountPoint) {
		$line = explode("\t", $disk);
		if(strlen($line[3]) > $longestMountPoint)
			$longestMountPoint = strlen($line[3]);
		return [
			"block" => $line[0],
			"used" => intval($line[1]),
			"total" => (intval($line[2]) + intval($line[1])),
			"mountpoint" => $line[3]
		];
	}, $disks);
	$width = intval(`tput cols`);
	$height = intval(`tput lines`);
	if($width != $oldWidth || $height != $oldHeight)
		echo "\e[2J\e[1;1H";
	$oldWidth = $width;
	$oldHeight = $height;
	foreach($disks as $id => $disk) {
		$percentage = ($disk["used"] * 100) / $disk["total"];
		$availWidth = $width - ($longestMountPoint + 17);
		$filled = round(($availWidth * $percentage) / 100);
		$bar = progressBarStr($percentage / 100, $availWidth);
		$percentageCentered = sprintf("%8.6f%%", $percentage);
		$percentageCentered = str_pad($percentageCentered, $width, " ", STR_PAD_BOTH);
		$format  = "\e[K\e[1m\e[%d;1H %s";
		$format .= "\e[K\e[1m\e[%d;1H %".($longestMountPoint).".s %s Used: %7s";
		$format .= "\e[K\e[1m\e[%d;1H %".($longestMountPoint).".s %s Free: %7s";
		$format .= "\e[K\e[1m\e[%d;1H %".($longestMountPoint).".s %s Total: %6s";
		echo sprintf($format,
			($id * 5) + 2, $percentageCentered, 
			($id * 5) + 3, "", $bar, toBytes($disk['used']),
			($id * 5) + 4, $disk["mountpoint"], $bar, toBytes($disk['total'] - $disk['used']),
			($id * 5) + 5, "", $bar, toBytes($disk['total']),
		);
	}
}
