#!/bin/php
<?php
date_default_timezone_set("Europe/Rome");
$discord = `pgrep -x "DiscordPTB"`;
if($discord == "" && $discord == null) {
	proc_close(proc_open('discord-ptb &', [], $__));
	sleep(2);
}
$hour = DateTime::createFromFormat("H:i:s a", date("H:i:s a"));
$allowedMax = DateTime::createFromFormat("H:i:s a", "2:40:00 am");
$allowedMin = DateTime::createFromFormat("H:i:s a", "9:30:00 am");
if($hour < $allowedMax || $hour > $allowedMin)
	`i3-msg 'scratchpad show'`;
else {
	$maxVis = $allowedMax->format("H:i a");
	$minVis = $allowedMin->format("H:i a");
	`notify-send "Discord is currently not available." "\n<b>Reason</b>: <i>Discord cannot be used between <b>$maxVis and $minVis</b>.</i>" --icon="/var/lib/flatpak/app/com.discordapp.Discord/current/active/files/share/icons/hicolor/256x256/apps/com.discordapp.Discord.png"`;
	`i3-msg '[class="discord"] move scratchpad'`;
}
