#!/bin/sh
# This is a modification of a script by luke smith, he wrote the majority of this, I only added support for rofi

xclip -h 2>/dev/null || exit 1

window=$(xdotool getwindowfocus)
chosen=$(cut -d ';' -f1 ~/.config/emoji | dmenu -w $window -i -l 20 | sed "s/ .*//")

[ "$chosen" != "" ] || exit

echo "$chosen" | tr -d '\n' | xclip -selection primary
echo "$chosen" | tr -d '\n' | xclip -selection clipboard

# If you run this command with an argument, it will automatically insert the character.
if [ -n "$1" ]; then
	xdotool key Shift+Insert
else
	notify-send "'$chosen' copied to clipboard." &
fi
