#!/bin/sh
# This is a modification of a script by luke smith, he wrote the majority of this, I only added support for rofi
xclip -h >/dev/null || exit

chosen=$(grep -v "#" -h ~/.config/emoji | rofi -dmenu -i -p "Emoji" -l 20 -fn Monospace-18)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "'$c' copied to clipboard." &

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | xclip
notify-send "'$s' copied to primary." &
